### ISSUE TITLE
Software does not exit after running against large data set

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-deep-archive#64]
**Describe the bug**
When running against the large insight bundle on pds-dev-el7, the software just hangs after it completes the document generation:
```
[jpadams@pds-dev-el7 ~]$ pds-deep-archive -s PDS_IMG -b https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/ /data/home/pds4/insight_cameras/bundle.xml
INFO 👟 PDS Deep Archive, version 0.1.0
INFO 🏃‍♀️ Starting AIP generation for /data/home/pds4/insight_cameras/bundle.xml
WARNING 📯 XML file /data/home/pds4/insight_cameras/catalog/catalog.xml lacks a logical_identifier; skipping it
INFO 🎉  Success! AIP done, files generated:
INFO • Checksum manifest: insight_cameras_v1.0_checksum_manifest_v1.0.tab
INFO • Transfer manifest: insight_cameras_v1.0_transfer_manifest_v1.0.tab
INFO • XML label for them both: insight_cameras_v1.0_aip_v1.0.xml
WARNING 🤚 Notice! --include-all-collections isn't yet supported; will assume it's enabled for now
INFO 🏃‍♀️ Starting SIP generation for /data/home/pds4/insight_cameras/bundle.xml

(hangs here)
```

I am guessing the database or something else is being left open, which is causing this bug?

**Comment by jordanpadams** [comment]
Looks like I got an error message when I tried to kill it:
```
^CTraceback (most recent call last):
  File "/home/jpadams/.virtualenvs/pds-deep-archive/bin/pds-deep-archive", line 11, in <module>
    load_entry_point('pds.deeparchive==0.1.0', 'console_scripts', 'pds-deep-archive')()
  File "/home/jpadams/.virtualenvs/pds-deep-archive/lib64/python3.6/site-packages/pds/aipgen/main.py", line 108, in main
    args.include_all_collections
  File "/home/jpadams/.virtualenvs/pds-deep-archive/lib64/python3.6/site-packages/pds/aipgen/sip.py", line 448, in produce
    hashedFiles = _getDigests(lidvidsToFiles, hashName)
  File "/home/jpadams/.virtualenvs/pds-deep-archive/lib64/python3.6/site-packages/pds/aipgen/sip.py", line 276, in _getDigests
    d = getDigest(url, hashName)
  File "/home/jpadams/.virtualenvs/pds-deep-archive/lib64/python3.6/site-packages/pds/aipgen/utils.py", line 73, in getDigest
    buf = i.read(_bufsiz)
KeyboardInterrupt
```
